server:
  port: 8080

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/orders
    username: postgres
    password: postgres
  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    enabled: false
